# ---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-wg
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging-ds
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging-ds
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging-ds
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd-gke
      serviceAccountName: fluentd-gke
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.11-debian-kafka-2
        command: ["/bin/sh"]
        args: ["-c", "gem install fluent-plugin-kafka && cp /fluent-config/fluent.conf /fluentd/etc/ && /fluentd/entrypoint.sh"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-config
          mountPath: /fluent-config
      terminationGracePeriodSeconds: 30   
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-config
        configMap:
          name: loggingappconfigmap
