
# Run with the command kubectl create -f rbac.yml
# apiVersion: v1
# kind: ServiceAccount
# metadata:
  # name: fluentd
  # namespace: kube-system 
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
  # name: fluentd
  # namespace: kube-system
# rules:
# - apiGroups: [""]
  # resources:
  # - containers
  # - pods
  # - namespaces
  # - services
  # verbs:
  # - get
  # - watch
  # - list

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
  # name: fluentd
  # namespace: kube-system
# subjects:
# - kind: ServiceAccount
  # name: fluentd # Name is case sensitive
  # namespace: kube-system
# roleRef:
  # kind: ClusterRole
  # name: fluentd
  # apiGroup: rbac.authorization.k8s.io
# ---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.11-debian-kafka-2
        # command: ["/bin/sh"]
        # args: ["-c", "gem install fluent-plugin-kafka && cp /fluent-config/fluent.conf /fluentd/etc/ && /fluentd/entrypoint.sh"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-config
          mountPath: /fluent-config
      terminationGracePeriodSeconds: 30   
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-config
        configMap:
          name: loggingappconfigmap